on: 
  push:
    tags:
      - 'v*'

jobs:
  training-pdf-builder:
    runs-on: ubuntu-latest
    name: Build the training PDF
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
      - name: Setup Nix
        uses: cachix/install-nix-action@v25
        with:
          nix_path: nixpkgs=channel:nixos-unstable      
      - name: Build PDF
        run: nix-build
      - name: Publish
        run:  gh release create ${{ github.ref_name }} result/master.pdf --verify-tag --generate-notes
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
